baseURL = "https://micahguttman.com"
languageCode = "en-us"
title = "Micah Guttman"
theme = "nametagHakim"
assetDir = "/assets"
publishDir = "docs"
[params]
    tagline = "Student, Developer, IT Professional, & Maker"
    name = "Micah Guttman"
    keywords = "Micah Guttman, Micah Shaw, Micah Guttman, memtech3, "
    [params.resume]
        resume = false
        link = "Resume 8-18-21.pdf"
    [params.sections]
        navbar = false
        downChevron = false
        bottomContent = false
        summary = false
        timeline = false
        skills = false
        moretocome = false
        footer = false
[menu]
    [[menu.main]]
    identifier = "about"
    name = "About Me"
    pre = "<i class='fa fa-heart'></i>"
    url = "#bottom-content"
    [[menu.main]]
    identifier = "more"
    name = "More"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"
    [[menu.main]]
    parent = "more"
    name = "getting finished"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"