baseURL = "http://example.org/"
languageCode = "en-us"
title = "Micah"
theme = "nametagHakim"
assetDir = "/assets"
[params]
    tagline = "Student, Developer, IT Professional, & Maker"
    name = "Micah Shaw Guttman"
